---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft

on:
  workflow_dispatch:
  pull_request:

jobs:

  # ShiftLeft Java analysis requires artifacts generated during Java build, stored
  # within a codebases's target binary.  Pre-processing for ShiftLeft Java analysis
  # therefore consists of building a codebase's target binary and making it available
  # to the ShiftLeft CLI for analysis.
  Prepare-Workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out Trigger Commit
        uses: actions/checkout@v3

      # The sample vulnerable codebase, ShiftLeft-Java, is written in Java 11, so the appropriate
      # version is set for the setup-java action.
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11.0.x

      - name: Build Java Binary
        run: mvn compile package

  Perform-ShiftLeft-Analysis:
    runs-on: ubuntu-latest
    needs: Prepare-Workspace
    
    steps:
      - name: Download ShiftLeft CLI
        run: |
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && \
          chmod a+rx ${GITHUB_WORKSPACE}/sl

      # The ShiftLeft CLI requires Java 1.8 for execution, so the appropriate
      # version is set for the setup-java action.
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Extract Branch Name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Perform ShiftLeft Analysis
        run: |
          ${GITHUB_WORKSPACE}/sl analyze --app shiftleft-java-demo \
            --strict --wait \
            --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} \
            --vcs-prefix-correction "io/shiftleft=src/main/java/" \
            --java --cpg \
            target/hello-shiftleft-0.0.1.jar
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        
  Build-Rules: 
    runs-on: ubuntu-latest
    needs: Perform-ShiftLeft-Analysis
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && \
        chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: Validate Build Rules
      run: |
        ${GITHUB_WORKSPACE}/sl check-analysis --app shiftleft-java-demo \
            --branch "${{ github.head_ref || steps.extract_branch.outputs.branch }}" \
            --report \
            --github-pr-number=${{github.event.number}} \
            --github-pr-user=${{ github.repository_owner }} \
            --github-pr-repo=${{ github.event.repository.name }} \
            --github-token=${{ secrets.GITHUB_TOKEN }}
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
         
  
